import healthData from "../../data/health-data.json";
import { getMorningBrief } from "../lib/brief";

// Re-generate the page (and its Gemini brief) at most once a day
export const revalidate = 86400;

type NumericKey =
  | "sleep_hours"
  | "screen_time"
  | "calories_in"
  | "calories_out"
  | "stand_hours"
  | "avg_heart_rate"
  | "gym_duration_mins";

const records = healthData.records;

function avg(key: NumericKey) {
  return records.reduce((acc, r) => acc + r[key], 0) / records.length;
}

function Sparkline({ values }: { values: number[] }) {
  const w = 140;
  const h = 40;
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  const x = (i: number) => (i / (values.length - 1)) * (w - 8) + 4;
  const y = (v: number) => h - 6 - ((v - min) / range) * (h - 12);
  const points = values.map((v, i) => `${x(i)},${y(v)}`).join(" ");
  const last = values[values.length - 1];
  return (
    <svg
      width={w}
      height={h}
      viewBox={`0 0 ${w} ${h}`}
      aria-hidden="true"
      className="shrink-0"
    >
      <polyline
        points={points}
        fill="none"
        stroke="#93c5fd"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx={x(values.length - 1)} cy={y(last)} r="3.5" fill="#2563eb" />
    </svg>
  );
}

export default async function Home() {
  const brief = await getMorningBrief();
  const latest = records[records.length - 1];
  const period = `${records[0].date} – ${latest.date}`;
  const today = new Date().toLocaleDateString("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "long",
  });

  const gymSessions = records.filter((r) => r.gym_duration_mins > 0).length;
  const totalGymMins = records.reduce((acc, r) => acc + r.gym_duration_mins, 0);

  const secondaryStats = [
    { label: "Calories in", value: `${Math.round(avg("calories_in"))}`, sub: "avg / day" },
    { label: "Calories out", value: `${Math.round(avg("calories_out"))}`, sub: "avg / day" },
    { label: "Stand hours", value: avg("stand_hours").toFixed(1), sub: "avg / day" },
    { label: "Heart rate", value: `${Math.round(avg("avg_heart_rate"))}`, sub: "avg bpm" },
    { label: "Gym sessions", value: `${gymSessions}`, sub: `of ${records.length} days` },
    { label: "Gym time", value: `${totalGymMins}`, sub: "total mins" },
  ];

  return (
    <main className="flex-1 p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* The one thing — morning brief hero */}
        <section className="bg-blue-900 text-white p-8 rounded-2xl shadow-sm">
          <div className="flex items-baseline justify-between gap-4">
            <p className="text-sm font-medium text-blue-200 uppercase tracking-wider">
              Your one thing today
            </p>
            <p className="text-sm text-blue-200">{today}</p>
          </div>
          {brief ? (
            <>
              <p className="mt-4 text-3xl font-semibold leading-snug text-balance">
                {brief.action}
              </p>
              <p className="mt-4 text-sm text-blue-100">{brief.reasoning}</p>
              {brief.sources.length > 0 && (
                <div className="mt-4 flex flex-wrap gap-2">
                  {brief.sources.map((source) => (
                    <span
                      key={source}
                      className="text-xs px-2.5 py-1 rounded-full bg-blue-800 text-blue-100"
                    >
                      {source}
                    </span>
                  ))}
                </div>
              )}
              <p className="mt-5 text-xs text-blue-300">
                Generated by Gemini from your health, calendar, email and spending data.
              </p>
            </>
          ) : (
            <p className="mt-4 text-lg text-blue-100">
              Your brief is unavailable. Set the{" "}
              <code className="font-mono text-blue-50">GEMINI_KEY</code> environment
              variable to enable it.
            </p>
          )}
        </section>

        <header className="flex flex-col gap-1">
          <h1 className="text-2xl font-bold tracking-tight">At a glance</h1>
          <p className="text-sm text-gray-600">
            {records.length}-day period · {period}
          </p>
        </header>

        {/* Lead tiles: sleep and screen time */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
            <p className="text-sm font-medium text-gray-600">Sleep</p>
            <div className="mt-2 flex items-end justify-between gap-4">
              <p className="text-5xl font-semibold">
                {avg("sleep_hours").toFixed(1)}
                <span className="text-xl font-medium text-gray-500"> h avg</span>
              </p>
              <Sparkline values={records.map((r) => r.sleep_hours)} />
            </div>
            <p className="mt-3 text-sm text-gray-600">
              Last night: <span className="font-semibold text-gray-900">{latest.sleep_hours} h</span>
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
            <p className="text-sm font-medium text-gray-600">Screen time</p>
            <div className="mt-2 flex items-end justify-between gap-4">
              <p className="text-5xl font-semibold">
                {avg("screen_time").toFixed(1)}
                <span className="text-xl font-medium text-gray-500"> h avg</span>
              </p>
              <Sparkline values={records.map((r) => r.screen_time)} />
            </div>
            <p className="mt-3 text-sm text-gray-600">
              Latest day: <span className="font-semibold text-gray-900">{latest.screen_time} h</span>
            </p>
          </div>
        </section>

        {/* Secondary stats */}
        <section className="grid grid-cols-2 md:grid-cols-3 gap-4">
          {secondaryStats.map((s) => (
            <div
              key={s.label}
              className="bg-white p-4 rounded-xl shadow-sm border border-gray-100"
            >
              <p className="text-sm font-medium text-gray-600">{s.label}</p>
              <p className="mt-1 text-2xl font-semibold">{s.value}</p>
              <p className="text-xs text-gray-500">{s.sub}</p>
            </div>
          ))}
        </section>
      </div>
    </main>
  );
}
